<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace bl\virtual_points;


use bl\virtual_points\behaviors\Point;
use yii\base\Component;
/**
 * @method addPoint(int $point, string $description = null)
 * @method takePoint(int $point, string $description = null)
 * @method getAllPoint()
 * @method getPoint()
 */
class Points extends Component
{
    public $ar_object;

    public $pk = null;

    public function behaviors()
    {
        return [
            'point' => [
                'class' => Point::className()
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}